# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio-indexer
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    hyperfuel_config: #TODO
      url: https://fuel.hypersync.xyz
    contracts:
      - name: Mira
        address:
          - 0xd2fcd65b786eabec06761e379ce5b6a714399f4a2f5fe44e73680392640e9b6d
        abi_file_path: abis/mainnet/mira-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: MintEvent
          - name: BurnEvent
          - name: CreatePoolEvent
          - name: SwapEvent
