# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio-indexer
ecosystem: fuel
networks:
  - id: 9889
    start_block: 0
    contracts:
      - name: Mira
        address:
          - 0x13620e7df155f0027d13172e9a8a3ec030d7a4f001fe72ff00636422a3093e07
        abi_file_path: abis/mainnet/mira-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: MintEvent
          - name: BurnEvent
          - name: CreatePoolEvent
          - name: SwapEvent
