# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio-indexer
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    hyperfuel_config: #TODO
      url: https://fuel.hypersync.xyz
    contracts:
      - name: Mira
        address:
          - 0xe68f7269cc74edfafd10de380288b89e8d419f3b456f78ba727a8cb0d679b163
        abi_file_path: abis/mainnet/mira-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: MintEvent
          - name: BurnEvent
          - name: CreatePoolEvent
          - name: SwapEvent
